### ISSUE TITLE
Doesn't seem to be working for Bootstrap Grids on Chrome

### ISSUE THREAD

**Issue by suthanbala** [ademilter/chrome-css-grid-highlighter#11]
I tried it on http://getbootstrap.com it doesn't seem to be working

**Comment by mattrock1** [comment]
This extension doesn't seem to be working for me either. The button has no effect on any page I've tried. (Chrome Version 60.0.3112.90. OS Sierra 10.12.6)

**Comment by ergenekonyigit** [comment]
@suthanbala this extention not about bootstrap or whatever css framework. This extension about new css feature named grid. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout
