### ISSUE TITLE
Does not work in Chrome on OSX

### ISSUE THREAD

**Issue by mattrock1** [ademilter/chrome-css-grid-highlighter#13]
Extension installed. Clicking icon/button does nothing. (Chrome Version 60.0.3112.90. OS Sierra 10.12.6)

**Comment by yasinguzel** [comment]
which web site

**Comment by mattrock1** [comment]
None I've tried with any success. Random sites. 

- https://www.webdesignerdepot.com/2016/10/20-essential-css-tricks-every-designer-should-know/
- http://www.hongkiat.com/blog/useful-css-tricks-you-might-have-overlooked/
- https://css-tricks.com/
- http://www.iisd.org/

**Comment by badcat** [comment]
@mattrock1 does it work here?  https://gridbyexample.com/examples/code/example1.html
This extension is expecting CSS Grid based code. If the site does not use CSS Grid, then the extension wouldn't yield a result.

**Comment by mattrock1** [comment]
Yes it does, @badcat. Thanks for pointing out the extension works specifically for CSS Grid based code. I understood it as grid based layout. Cheers to ya.
