### ISSUE TITLE
Doesn't work when grip-gap not have

### ISSUE THREAD

**Issue by ergenekonyigit** [ademilter/chrome-css-grid-highlighter#16]
e.g. => https://css-tricks.com/

**Comment by ahmtaras** [comment]
@ergenekonyigit 
Actually it works. I tested it without using grid-gap, it works as follows.
I think there is something blocking the css-tricks too.

![adsiz](https://user-images.githubusercontent.com/23402407/29571499-06c3a16c-8762-11e7-9307-eb1a45b6c64b.png)
