### ISSUE TITLE
#documentin altındaki html taglarının grid özelliğine bakmıyor

### ISSUE THREAD

**Issue by yasinguzel** [ademilter/chrome-css-grid-highlighter#2]
![screen shot 2017-08-08 at 15 25 43](https://user-images.githubusercontent.com/16020123/29071857-0c3bc4cc-7c4e-11e7-897e-04efbda78713.png)
CodePen de yazılan sonuçlar "#document" in altında olduğundan ve kodda da "#document"in altındaki html elemanlarına bakılmadığından işaretleme yapmıyor.

**Comment by ademilter** [comment]
iframe içindeki datayı henüz taramıyorum. geliştirilebilir
