### ISSUE TITLE
Feature Request - Change color of Grid

### ISSUE THREAD

**Issue by badcat** [ademilter/chrome-css-grid-highlighter#3]
Would like a simple way to change the color(s) of the grid highlighter. 
Maybe all colors could rely on currentColor instead of hardcoded in the js?

Thank you for this.

**Comment by yasinguzel** [comment]
Added b34d6e6ee3e7390f8546e28029f4f8d139b74cf2

**Comment by ademilter** [comment]
@yasinguzel efsane olmuş helal

**Comment by yasinguzel** [comment]
@ademilter teşekkürler abi asıl proje efsane. 😄
